"""add_category_field_in_product_model

Revision ID: d34b82694cc1
Revises: fd46bdcc99d0
Create Date: 2026-09-23 07:04:43.343014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd34b82694cc1'
down_revision: Union[str, Sequence[str], None] = 'fd46bdcc99d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Agregar la columna como nullable para no fallar con filas existentes
    op.add_column(
        'app_inv_products',
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # 2. Rellenar filas existentes (el enum se guarda por nombre: 'MOUSE')
    op.execute("UPDATE app_inv_products SET category = 'MOUSE' WHERE category IS NULL")
    # 3. Ahora sí, NOT NULL
    op.alter_column('app_inv_products', 'category', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_inv_products', 'category')
    # ### end Alembic commands ###
